function [path] = floyd_warshall_path(src,dest,next)
%FLOYD_WARSHALL_PATH Reconstruct the path with the path matrix generated by
%the Floyd Warshall algorithm
path = [];
if next(src,dest) == -1
    return;
end
path = [src];

c_node = src;
while c_node ~= dest
    c_node = next(c_node,dest);
    path = [path, c_node];
end

end

